name: GitHub Actions Test - GO
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a {{ github.event_name }} event."
      - run: echo "repository name is  ${{ github.repository}}, branch ${{ github.ref }}"
      - run: echo "workspace ${{ github.workspace }}"
      - run: ls ${{ github.workspace }}
      
      # # use specific version, see 'using multiple versions of Go' as an alternative
      # - name: Setup Go 1.21.x
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.21'
      #     check-latest: true
      #     cache-dependency-path: ${{github.workspace}}/go.sum

      # - name: Install dependencies
      #   run: |
      #     go get github.com/gin-gonic/gin
      #     go get gorm.io/driver/sqlite
      #     go get gorm.io/gorm
      # - name: Build
      #   run: go build -v practice-go
      # - name: Test
      #   run: go test -v
      # - name: Upload Go test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Go-results
      #     path: TestResults.json
